<?php

namespace App\Models;

use App\Observers\ReplyObserver;

class Reply extends Model
{
    protected $fillable = ['content'];

    public static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated

        static::observe(new ReplyObserver());
    }

    public function topic()
    {
        return $this->belongsTo(Topic::class);
    }

    public function user()
    {
        return $this->belongsTo(User::class,'user_id', 'id');
    }
}
